version: "3.8"
services:
  backend:
    image: blog-backend:0.0.1
    build:
      context: ./backend
      args:
        JAR_FILE: blog-0.0.1-SNAPSHOT.jar
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:16.1
    volumes:
      - .volumes/postgres/:/var/lib/postgres/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blog
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "admin", "-d", "blog"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 60s
