version: "3.8"
services:
  backend:
    image: blog-backend:0.0.1
    build:
      context: ./backend
      args:
        JAR_FILE: blog-0.0.1-SNAPSHOT.jar
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/blog
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      db:
        condition: service_healthy
    # healthcheck:
    #   test: "curl --fail --silent localhost:8080/actuator/health | grep UP || exit 1"
    #   interval: 30s
    #   timeout: 60s
    #   retries: 5
    #   start_period: 60s

  db:
    image: postgres:16.1
    volumes:
      - .volumes/postgres/:/var/lib/postgres/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blog
      POSTGRES_HOST_AUTH_METHOD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 60s
